# fly.toml app configuration file generated for 3-1-3-11-divine-shadow-4661-proud-sun-1948-floral-forest-6872 on 2024-01-06T08:49:10+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "3-1-3-11-divine-shadow-4661-proud-sun-1948-floral-forest-6872"
primary_region = "sin"

[build]

[env]
  PORT = "3000"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
